# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdd0e235dde608fc0b0da233eeb0fc88e033852b0f1a0bc044d52d96cab464037056fdc62ed2fd1863e9c4ee33ba824e150e97da47a7b6ce13435374385f2f81

test:
  secret_key_base: 16770680218601e077e046a1a56b77a35594ff8e96df254268d59bf6fedd02b6b20512abc286d3cdeef651fc4f79c522093e15a50a4e6a18155d73d3bedbe3cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
